### ISSUE TITLE
Policy name is empty when edit an existing policy

### ISSUE THREAD

**Issue by Amy0511** [boomerang-io/bosun.client.web#22]
![Screen Shot 2021-08-13 at 1.54.18 PM.png](https://images.zenhubusercontent.com/60fa2d844a9736b3ab8df6cc/0d0c729f-081a-46f9-89c4-2074b34be902)

The input of name should have the existing policy name as default.

**Comment by HenryZhuhongyin** [comment]
it is fixed in the current typescript version. @Amy0511 please double-check and close it
![image](https://user-images.githubusercontent.com/87843839/130052187-bb135d55-d9d9-4b7d-af61-884c4f6efd66.png)

**Comment by Amy0511** [comment]
Fixed.

**Comment by Amy0511** [comment]
Fixed in main branch
